section and container for main content
NGO-AQE/NGO-AQE-Project pull request #11
Opened 2024-07-19 19:20 UTC by pawelkloc

2024-07-20 17:10 UTC, JustinNowoczek approved these changes

2024-07-21 08:17 UTC, Davwidos requested changes

2024-07-21 08:17 UTC, Davwidos commented on src/styles/sectionAndContainer.module.scss
I got this kind of error when i tried to use this scss module:
```
[vite] Internal server error: [sass] Mixin doesn't accept a content block.
   ┌──> src\styles\sectionAndContainer.module.scss
20 │         @include f.big-text {
   │         ^^^^^^^^^^^^^^^^^^^ invocation
   ╵
   ┌──> src\styles\fonts.scss
47 │ @mixin big-text {
   │        ━━━━━━━━ declaration
   ╵
  src\styles\sectionAndContainer.module.scss 20:9  root stylesheet
```
You should include fonts without content inside like this: `@include f.big-text;`

2024-07-21 10:43 UTC, Davwidos approved these changes

2024-07-21 11:09 UTC, merged