done
NGO-AQE/NGO-AQE-Project pull request #24
Opened 2024-07-26 09:48 UTC by JustinNowoczek

also started creating the document types

2024-07-29 07:23 UTC, danon321 requested changes

2024-07-29 07:23 UTC, danon321 commented on src/App.tsx
> +  const bts = ['en', 'pl', 'de'].map(l => (
Tutaj jezeli chodzi o te tablice z jezykami to wolałbym aby pochodziła ona z jednego miejsca. Czyli np z jakiegos globalnego obiektu w folderze Constants czy cos takiego

2024-07-29 07:23 UTC, danon321 commented on src/SanityContext.tsx
> +  const [selectedLanguage, setSelectedLanguage] = useState('en'); //this is just the language code
tak jak wyzej

2024-07-30 06:02 UTC, Davwidos requested changes
After page reload there is not found error
![image](https://github.com/user-attachments/assets/977ca16a-517d-4793-85cc-45c93db9e87b)

2024-07-30 10:50 UTC, Davwidos approved these changes

2024-07-31 07:38 UTC, danon321 approved these changes

2024-07-31 07:38 UTC, merged