basic version
NGO-AQE/NGO-AQE-Project pull request #25
Opened 2024-07-26 14:46 UTC by YarynaPuhach

2024-07-31 07:59 UTC, JustinNowoczek commented
Add to app plz TT

2024-08-05 11:01 UTC, marinatea requested changes
na ekranie 640-743 się rozjeżdża. i odstęp na dole na tablecie trzeba poprawić :)

2024-08-05 13:57 UTC, JustinNowoczek approved these changes

2024-08-09 07:55 UTC, marinatea approved these changes

2024-08-12 07:45 UTC, merged