finished section
NGO-AQE/NGO-AQE-Project pull request #5
Opened 2024-07-16 13:19 UTC by weswojciech

2024-07-17 09:29 UTC, Davwidos requested changes

2024-07-17 09:29 UTC, Davwidos commented on src/components/WhyAQE/WhyAQE.tsx
> +      </div>
I would be be better to create component for `why_section` insted of repeating code

2024-07-17 09:29 UTC, Davwidos commented on src/App.tsx
> +      <WhyAQE />
I think to avoid future conflicts will be better to remove it from App.tsx and add it later to the right place

2024-07-17 11:29 UTC, marinatea requested changes
Jeśli używamy scss moduls, czy nie trzeba w stylach komponentów używać rozszerzenia .module.scss, żeby było jasne o co chodzi?

2024-07-17 16:10 UTC, Davwidos requested changes

2024-07-17 16:10 UTC, Davwidos commented on src/components/WhyAQESubSection/WhyAQESubSection.module.scss
Styling of `WhyAQESubSection` uses same BEM block as `WhyAQE` . I think it would be good idea to put folder `WhyAQESubSection` inside `WhyAQE` and import single same scss module.

2024-07-19 09:15 UTC, Davwidos requested changes

2024-07-19 09:15 UTC, Davwidos commented on src/components/WhyAQE/WhyAQE.tsx
I mean somthing more like this: 
```
const subsections = [
{ icon: data, title: data, text: data }
...
]
```

and in component:
```
subsections.map(data => <WhyAQESS key={data.title} {...data}) />)
```
or 
```
subsections.map(data => <WhyAQESS key={data.title} data={data} />)
```

2024-07-19 15:27 UTC, JustinNowoczek commented
Reminding of the class naming issue mentioned on the meeting.

2024-07-22 06:16 UTC, JustinNowoczek reviewed
why do you have both an scss and module.scss file, when they are almost identical.

2024-07-23 08:50 UTC, Davwidos requested changes
Section is not in center
![image](https://github.com/user-attachments/assets/d77074ab-f301-48ee-a083-2c5df8b54305)

2024-07-24 08:47 UTC, JustinNowoczek approved these changes

2024-07-25 11:50 UTC, merged