Button Component
NGO-AQE/NGO-AQE-Project pull request #8
Opened 2024-07-17 09:36 UTC by marinatea

https://app.clickup.com/t/86951t5rx

2024-07-17 16:47 UTC, weswojciech commented
I don't know if it's done properly with children etc. Seems weird. Need someone else to review

2024-07-18 12:08 UTC, Davwidos requested changes
I think all beside title prop its good. You can also use `React.ComponentProps<"button">` , that will allow to pass all button attributes to component, but i think as it is also works well.

2024-07-18 12:09 UTC, Davwidos commented on src/components/button/Button.tsx
> +      {children || title}
title prop i unnecesery here if button have no children it will be empty

2024-07-18 13:45 UTC, Davwidos approved these changes

2024-07-18 14:55 UTC, weswojciech approved these changes

2024-07-22 07:46 UTC, merged